### ISSUE TITLE
[2] Correr localmente el primer proyecto

### ISSUE THREAD

**Issue by laura3arual** [plentycode/PlentyCode#5]
Para este ticket ya debes tener configurado tu ambiente local y tener acceso al repositorio en Github. 

_**Recuerda**: Antes de empezar a trabajar en este ticket, muévelo a la columna "In progress". Ve marcando los pasos a medida que los completas y cuando tengas todos los pasos listos, mueve el ticket a la columna "Review in progress"._
### Requerimientos

- [x] Clonar el repositorio [PlentyCode](https://github.com/plentycode/PlentyCode)
- [x] Desde la terminal de Visual Studio Code ubicarse en la carpeta /public del repositorio (`cd public`)
- [x] Ejecutar `npx http-server `
- [x] Abrir en el navegador la url que sale en la Terminal
- [x] Tomar un screenshot de la aplicación que se muestra en el navegador

### Recursos
Recursos que te pueden servir de apoyo: 

- Cómo clonar un repo, sólo la parte de clonar, (hasta el minuto 1:47): https://www.youtube.com/watch?v=kw72-dm7yNI
- Cómo usar el comando CD: https://www.youtube.com/watch?v=ycOzl0coFxA

**Comment by Jonatancarrillo** [comment]
![Captura de pantalla de 2021-09-22 13-11-50](https://user-images.githubusercontent.com/91024657/134398620-bbda70dc-6d6c-4001-8ae1-f0f6ad9536f6.png)

**Comment by civan** [comment]
Well done!
