### ISSUE TITLE
[3] Mi primer Pull request

### ISSUE THREAD

**Issue by laura3arual** [plentycode/PlentyCode#6]
_**Recuerda**: Antes de empezar a trabajar en este ticket, muévelo a la columna "In progress". Ve marcando los pasos a medida que los completas y cuando tengas todos los pasos listos, mueve el ticket a la columna "Review in progress"._

### Requerimientos
- [x] Revisar el video de flujo de trabajo con pull request que se encuentra en los recursos de este ticket (Éste será el flujo que usaremos de ahora en adelante para entregar los desarrollos).

En el proyecto PlentyCode:
- [x] Crear un branch local basado en la rama master
- [x] Dentro de la carpeta workspaces crear una carpeta con tu nombre de usuario de la cuenta de Github.
- [x] Dentro de esta carpeta se debe crear una versión exacta del sitio de PlentyCode que se encuentra en la carpeta public
- [x] Para correr esta nueva versión en el navegador, desde la terminal debes ingresar a la carpeta workspaces/{nombre_de_usuario} y ejecutar `npx http-server`
- [x] Agregar el ícono de linkedIn a la página web con el siguiente link: https://www.linkedin.com/company/plentycode/ (de esta forma quedarían los links youtube, twitter y linkedin, el código del Symbol de svg lo[ puedes encontrar aquí](https://drive.google.com/file/d/1EcGCfrFgLTT27qVYsYbTIuBUru6YuejV/view?usp=sharing).
- [x] Crear el commit con los cambios realizados.
- [x] Crear el pull request en Github apuntando al branch de master, y asocia el Pull Request con esta tarea.
- [x] Síguenos en LinkedIn (crea tu cuenta si aún no la tienes) y si te es posible, agréganos como tu puesto de trabajo. 

### Recursos
Recursos que te pueden servir de apoyo: 

- Como crear un Pull Request: https://www.youtube.com/watch?v=-VP02PX6QSY
- Habilitar comando `code .` en la terminal: https://code.visualstudio.com/docs/setup/windows 
![image](https://user-images.githubusercontent.com/4790488/134353863-4db90250-b6d6-456d-8afb-ae4b7d0f5e27.png)

**Comment by Leidylro** [comment]
![image](https://user-images.githubusercontent.com/91025393/134611219-c4939385-1eb4-4691-9e30-aa682a34878a.png)

**Comment by laura3arual** [comment]
Good job!
