### ISSUE TITLE
[13] Juego de CSS Flexbox Flexbox Froggy

### ISSUE THREAD

**Issue by laura3arual** [plentycode/PlentyCode#93]
_En este ticket aprenderás aprenderás y repasarás el uso de CSS Flexbox jugando._

### Requerimientos
- [x] Seguir las instrucciones del juego https://flexboxfroggy.com/#es.
- [x] Completa los 32 niveles del juego y responde con un screenshot como evidencia.

### Recursos
- Guía de Flexbox: https://www.youtube.com/watch?v=Y6yviDqdMc8

_Recuerda buscar en internet, y si encuentras un recurso que te ayude a resolver este ticket, por favor déjalo en los comentarios de esta forma ayudarás otros estudiantes_

**Comment by Jonatancarrillo** [comment]
![2021-12-23 (2)](https://user-images.githubusercontent.com/91024657/147272843-a10d87a7-4331-4ca1-8862-7e73deb0c4f0.png)
Resolves
